// This file is code-generated by running:
//
//   $ ignite generators make-screen-map

import * as UI from '..'

export default {
  account: UI.AccountScreen,
  changePasswordFromToken: UI.ChangePasswordFromTokenScreen,
  changePassword: UI.ChangePasswordScreen,
  changeProfile: UI.ChangeProfileScreen,
  completedOrderList: UI.CompletedOrderListScreen,
  contact: UI.ContactScreen,
  currentOrderList: UI.CurrentOrderListScreen,
  dashboard: UI.DashboardScreen,
  faq: UI.FaqScreen,
  forgot: UI.ForgotScreen,
  login: UI.LoginScreen,
  orderConfirmation: UI.OrderConfirmationScreen,
  orderReview: UI.OrderReviewScreen,
  order: UI.OrderScreen,
  pastReferrals: UI.PastReferralsScreen,
  paymentMethodList: UI.PaymentMethodListScreen,
  paymentMethod: UI.PaymentMethodScreen,
  personal: UI.PersonalScreen,
  privacyPolicy: UI.PrivacyPolicyScreen,
  product: UI.ProductScreen,
  referralIntro: UI.ReferralIntroScreen,
  scanHome: UI.ScanHomeScreen,
  scan: UI.ScanScreen,
  shippingAddressList: UI.ShippingAddressListScreen,
  shippingAddress: UI.ShippingAddressScreen,
  signup: UI.SignupScreen,
  termsOfUse: UI.TermsOfUseScreen
}
